title: Jacob's Blog
author: Jacob Collins
email: jacob.edward.collins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the webpage I have created for the Prework activities in 
  week 1 of the Awesome Inc U Bootcamp. I'm looking forward to all of the skills
  I'm going to learn in the weeks ahead!
theme: minima
# social links
twitter_username: J_coll13 # DO NOT include the @ character, or else the build will fail!
github_username:  jec1342 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
